version: '3.1'

services:
  postgres:
    container_name: student-web-postgres
    image: postgres:12.4
    restart: always
    ports:
      - "5454:5432"
    environment:
      POSTGRES_DB: student_web
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
